<?php

/**
 * @file
 * Contains league_lineup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function league_lineup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the league_lineup module.
    case 'help.page.league_lineup':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Generates lineup information for games') . '</p>';
      return $output;

    default:
  }
}
